# Bret-MBR.local specifc env vars

# Homebrew
export HOMEBREW_ROOT=/usr/local

# Editors
export EDITOR='vim'
export VISUAL='subl'
export GIT_EDITOR='vim'

# Colors

# Enables terminal colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# Sets the color of the root prompt
export SUDO_PS1="\[\e[33;1;41m\][\u] \w \$\[\e[0m\] "
# Sets the color of the default prompt.  I did it myself!
export PS1="\[\e[33;1;32m\]\h:\[\e[33;1;34m\]\W \u\$\[\e[0m\] "

# Sets up 256 Color in VI under screen
# http://www.robmeerman.co.uk/unix/256colours
# Relates to something in .vimrc
if [ ! -z "$TERMCAP" ] && [ "$TERM" == "screen" ]; then
    export TERMCAP=$(echo $TERMCAP | sed -e 's/Co#8/Co#256/g')
fi


# Environment specific vars:
if [ -f $HOME/.env ]; then
  source $HOME/.env
fi

# Special Paths

function prepend_path {
  if [ -d $1 ]; then
    export PATH=$1:$PATH
  fi
}

function append_path {
  if [ -d $1 ]; then
    export PATH=$PATH:$1
  fi
}

function source_it {
  if [ -f $1 ]; then
    source $1
  fi
}

# homebrew http://brew.sh
#if [[ ! -z "$HOMEBREW_ROOT" ]]; then
#  export PATH=$HOMEBREW_ROOT/bin:$HOMEBREW_ROOT/sbin:$PATH
#fi

# Ruby
if [ -d $(brew --prefix)/opt/ruby/bin ]; then
  # Homebrew Ruby (homebrew caveats)
  export PATH=$(brew --prefix)/opt/ruby/bin:$PATH
else
  # rbenv
  if which rbenv > /dev/null; then
    eval "$(rbenv init -)";
  fi
fi

# Haskell Cabal
append_path $HOME/.cabal/bin

# Go
if [ -d $HOME/.go ]; then
  # Go Path (http://golang.org/doc/code.html#GOPATH)
  export GOPATH=$HOME/.go
  export PATH=$PATH:$GOPATH/bin
fi
# Go bin path (homebrew)
append_path $(brew --prefix)/opt/go/libexec/bin

# Enable .bash_aliases
if [ -f $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases
fi

# Completion

# Enable bash-completion2
if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
   source $(brew --prefix)/share/bash-completion/bash_completion
fi
