---
- name: Install homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/versions
    - homebrew/dupes

- name: Check time of last update
  command: git log -1 --format="%ct" HEAD
  args:
    chdir: /usr/local
  register: timestamp
  always_run: yes

- name: stat HOMEBREW_LIBRARY
  stat: path=/usr/local/Library
  register: library

- name: conditionally update homebrew
  homebrew: update_homebrew=yes
  when: ansible_date_time.epoch|int - timestamp.stdout|int > 60 * 60 * 24

- name: Install dev software with homebrew
  homebrew:
    name={{ item }}
    state=present
  with_items:
    - cask
    - git
    - node
    - python
    - python3
    - vim

- name: check for existing ~/.env file
  stat: path={{ ansible_env.HOME }}/.env follow=true
  register: env_file

- name: Put homebrew in front of path
  lineinfile: dest={{ ansible_env.HOME }}/.env
    line="if hash brew 2>/dev/null; then
        export PATH=$(brew --prefix)/bin:$PATH ;
      fi"
  when: env_file.stat.exists and ansible_distribution == "MacOSX" and {{ ansible_distribution_version | version_compare('10.9.5', '<=') }}

- name: install ruby
  homebrew:
    name=ruby
    state=present
  with_items:
    - ruby

- name: set up ruby paths
  lineinfile: dest={{ ansible_env.HOME }}/.env
    line="RUBY_PATH=$(brew --prefix)/opt/ruby/bin ;
      if [ -d $RUBY_PATH ]; then
        export PATH=$RUBY_PATH:$PATH ;
      else if which rbenv > /dev/null ; then
        eval $(rbenv init -);
        fi ;
      fi"
  when: env_file.stat.exists
  tags:
    - dotfiles

- name: install go
  homebrew:
    name=go
    state=present

- name: set up GOROOT bin path
  lineinfile: dest={{ ansible_env.HOME }}/.env
    line="if [ -d $(brew --prefix)/opt/go/libexec/bin ]; then
      export PATH=$PATH:$(brew --prefix)/opt/go/libexec/bin ;
    fi"
  tags:
    - dotfiles
  when: env_file.stat.exists

- name: create GOPATH folders
  file:
    path="{{ gopath }}"
    state=directory
  with_items:
    - "{{ gopath }}"
    - "{{ gopath }}/bin"
    - "{{ gopath }}/src/github.com/bcomnes/"

- name: set up GOPATH
  # Go Path (http://golang.org/doc/code.html#GOPATH)
  lineinfile: dest={{ ansible_env.HOME }}/.env
    line="if [ -d $HOME/go ]; then
      export GOPATH=$HOME/go ;
      export PATH=$PATH:$GOPATH/bin ;
    fi"
  tags:
    - dotfiles
  when: env_file.stat.exists

- name: install bash_completion2
  homebrew:
    name=bash-completion2
    state=present
  when: False

- name: enable bash_completion2
  lineinfile: dest={{ ansible_env.HOME }}/.bash_env
    line="if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
      . $(brew --prefix)/share/bash-completion/bash_completion ;
      fi"
  when: False
