 # Ensure our vim directory exists
- name: Install dev software with homebrew
  homebrew:
    name=vim
    state=present

- name: ensure .vim directory exists
  file:
    dest={{ ansible_env.HOME }}/.vim/{{ item }}
    state=directory
  with_items:
    - backup
    - colors
    - tmp
    - undo
    - view

- name: link vimrc file into place
  file: src={{ item }} dest={{ ansible_env.HOME }}/.{{ item | basename }} state=link
  with_fileglob:
    - ./vimrc

- name: link color files
  file: src={{ item }} dest={{ ansible_env.HOME }}/.vim/colors/{{ item | basename }} state=link
  with_fileglob:
    - ./vim/colors/*
