---
- name: Install cask software
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - airfoil
    - appcleaner
    - arduino-beta
    - flash
    - java
    - atom
    - bonjour-browser
    - keepingyouawake
   # - daisydisk
    - dropbox
    - firefox
    - google-chrome
    - flickr-uploadr
    - flux
    - fritzing
    - rowanj-gitx
    - imageoptim
    - linein
    - magicprefs
    - moom
    - nicecast
    - mou
    - mysqlworkbench
    - omnigraffle
    - omnioutliner
    - omniplan
    - piezo
    - processing
    - bittorrent-sync
    - opendns-updater
    - skim
    - the-unarchiver
    - things
    - textmate
    - time-sink
    - transmission
    - transmit
    - vlc
    - xld
    - steam
    - mactracker
    - inkscape
    - keepassx
    - kismac
    - screenflow
    # Requires Sudo
    - xquartz
    - virtualbox
    - vagrant
